### ISSUE TITLE
Flexible token refill time interval

### ISSUE THREAD

**Issue by Sogii** [AkBoy7/AkBot-Public#20]
Can you change the time in which you get a new token to every 2 weeks, and make it so we can easily change it with either a command or in the code or something?

**Comment by AkBoy7** [comment]
this is done inside the tokenManager.js file. On line 9 the token is refilled at 01-XX-XXXX (the first day of every month). With the current implementation of the [cron](https://reflectoring.io/schedule-cron-job-in-node/) library used here, it is not possible to do a job every 2 weeks but there is a workaround by doing it on the first day of every month and every 15th day of the month. 

As seen in the code snippet below on how this would change the code then:

```javascript
const job = schedule.scheduleJob('* * 1,15 * *', async function(){
```

**Comment by Sogii** [comment]
yeah that works, might need to be changed every other month or so to fine-tune the refresh amount but should be cool
